name: Integração Contínua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

  discord:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Notificar Discord (SUCESSO)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "✅ Build e testes passaram com sucesso 🚀"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notificar Discord (ERRO)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "❌ Falha no build ou nos testes ⚠️"}' \
          ${{ secrets.DISCORD_WEBHOOK }}